In [ ]:
from keras.models import load_model
import numpy as np
import tensorflow as tf
import pathlib

In [ ]:
#ส่วนนี้คือการโหลด model
model = load_model('/content/drive/MyDrive/Project/Prediction-of-Monocots-and-Dicotyledon.h5')

In [ ]:
#ส่วนนี้จะเป็น การสร้าง pathไปยัง โฟลเดอร์ Test_leaf
test_leaf_url = "/content/drive/MyDrive/Project/Test_leaf"
test_leaf = pathlib.Path(test_leaf_url)
##ส่วนนี้จะนับภาพที่พบในนามสกุล jpg 
image_count = len(list(test_leaf.glob('*.jpg')))
print(image_count)

9


In [ ]:
#ส่วนนี้คือ loop นำภาพมา Test model
for i in range(1, (image_count + 1)):
  #ส่วนของ path ของรูป
    leaf_picture = "/content/drive/MyDrive/Project/Test_leaf/" + str(i) + ".jpg"
# โหลดข้อมูลของรูป
    img = tf.keras.utils.load_img(
        leaf_picture, target_size=(180, 180)
    )

    img_array = tf.keras.utils.img_to_array(img) 
    img_array = tf.expand_dims(img_array, 0)

    classNames  = ["Dicotyledon","Monocotyledon"]
#ทำนายรูปภาพ
    prediction = model.predict(img_array)
    score = tf.nn.softmax(prediction[0])
    print(score)

    score_Class=classNames[np.argmax(score)]
    print(score_Class)
    #ส่วนนี้จะเป็นส่วนแสดงผลการทำนาย
    if(score_Class=='Monocotyledon'):
        print(
        "ภาพที่ " + str(i) + " น่าจะเป็นของภาพพืชในประเภทใบเลี้ยงเดี่ยว({}), ที่ค่าความเชื่อมั่น {:.2f} เปอร์เซ็นต์."
        .format(score_Class, 100 * np.max(score))
    )
    else: print(
        "ภาพที่ " + str(i) + " น่าจะเป็นของภาพพืชในประเภทใบเลี้ยงคู่({}), ที่ค่าความเชื่อมั่น {:.2f} เปอร์เซ็นต์."
        .format(score_Class, 100 * np.max(score))
    )

tf.Tensor([9.9981886e-01 1.8117297e-04], shape=(2,), dtype=float32)
Dicotyledon
ภาพที่ 1 น่าจะเป็นของภาพพืชในประเภทใบเลี้ยงคู่(Dicotyledon), ที่ค่าความเชื่อมัน 99.98 เปอร์เซ็นต์.
tf.Tensor([0.9965199  0.00348013], shape=(2,), dtype=float32)
Dicotyledon
ภาพที่ 2 น่าจะเป็นของภาพพืชในประเภทใบเลี้ยงคู่(Dicotyledon), ที่ค่าความเชื่อมัน 99.65 เปอร์เซ็นต์.
tf.Tensor([9.7978307e-07 9.9999905e-01], shape=(2,), dtype=float32)
Monocotyledon
ภาพที่ 3 น่าจะเป็นของภาพพืชในประเภทใบเลี้ยงเดี่ยว(Monocotyledon), ที่ค่าความเชื่อมัน 100.00 เปอร์เซ็นต์.
tf.Tensor([0.058571 0.941429], shape=(2,), dtype=float32)
Monocotyledon
ภาพที่ 4 น่าจะเป็นของภาพพืชในประเภทใบเลี้ยงเดี่ยว(Monocotyledon), ที่ค่าความเชื่อมัน 94.14 เปอร์เซ็นต์.
tf.Tensor([6.948910e-04 9.993051e-01], shape=(2,), dtype=float32)
Monocotyledon
ภาพที่ 5 น่าจะเป็นของภาพพืชในประเภทใบเลี้ยงเดี่ยว(Monocotyledon), ที่ค่าความเชื่อมัน 99.93 เปอร์เซ็นต์.
tf.Tensor([7.229859e-07 9.999993e-01], shape=(2,), dtype=float32)
Monocotyledon
ภาพที่ 6 น่าจะเป็นของ